remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Creative Commons Certificate Learning Space
description: This site is built and maintained by Anneliese Eber to support the learning objectives, outcomes, and assignments for the Creative Commons Certificate for Academic Librarians.
